"""Fix model order

Revision ID: 18ca211a8c52
Revises: 
Create Date: 2025-03-05 05:32:07.957006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ca211a8c52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('image_url')
        batch_op.drop_column('product_name')
        batch_op.drop_column('date_added')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), nullable=False))
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
